
import sys
import os
# Add the project root to the path to allow direct imports
sys.path.insert(0, os.path.abspath(os.path.dirname(os.path.dirname(__file__))))
from agents.base import BaseAgent

class ReadmeWriterAgent(BaseAgent):
    def run(self, input_data):
        features = input_data.get("features", [])
        content = """# Project: Sankalpa\n\nThis project was generated by the Sankalpa AI system.\n\n## Features\n
        # 🚀 Sankalpa — The AI Operating System for Building Software

Sankalpa is a modular, intelligent, memory-aware AI platform that helps you build full-stack, production-grade software apps using interconnected agents.

---

## 📦 Features

- 🧠 Modular Agent Architecture (Builder, Tester, Planner, Copilot)
- 🔁 Agent Chaining with Memory Integration
- 🔍 Prompt-based Task Planner & Executor
- 🧩 Plugin Loader + Self-Replicating Agent Generator
- 🖥️ Drag-and-Drop Visual Composer (React Flow)
- ⚙️ CLI & VS Code Extension Integration
- 🧪 Test Suite, Security Audit, LLM Fine-Tuning
- 📄 Autogenerated README, SEO, Pitch Deck, Launch Copy
- 🚀 Deploy-ready (Vercel/Render) + GitHub Actions CI

---

## 📂 Project Structure

```
/agents              # All modular agents (builder, tester, enhanced...)
/backend             # FastAPI backend (optional)
/catalog             # Agent catalog + plugin registry
/cli                 # CLI runner for terminal use
/frontend            # Next.js UI (Composer, Playground, Memory Viewer)
/logs                # Run logs, version history
/memory              # Session memory management
/scripts             # Deploy scripts, fine-tuning, linking
/vscode-extension    # Extension trigger with CLI agent runner
```

---

## 🔧 Getting Started

### 1. Clone the repo
```bash
git clone https://github.com/yourusername/sankalpa.git
cd sankalpa
```

### 2. Install dependencies
```bash
# Python backend (optional for API)
pip install -r requirements.txt

# Frontend
cd frontend
npm install
```

### 3. Start the development servers
```bash
# Frontend
cd frontend
npm run dev

# Backend (if used)
uvicorn backend.main:app --reload
```

---

## ▶️ How to Use

### 🧠 Run Agents via CLI
```bash
python cli/cli.py run-agent auth_builder
```

### 🖥️ Use Visual Composer
- Go to `http://localhost:3000/composer`
- Add agents, connect nodes
- Click **Run Chain** to execute
- Click **Save Chain** to export chain JSON

### 🤖 Use Copilot
- Enter a natural prompt in `/playground`
- Copilot suggests the next logical agent

### 🔌 Load Plugin
```bash
python cli/cli.py run-agent plugin_loader --plugin my_plugin
```

---

## 🚀 Deploying Sankalpa

### With Vercel
```bash
npm run build
vercel --prod
```

### Link custom domain
```bash
bash scripts/link_domain.sh
```

---

## 📣 Launch

- Use `/launch/post.md` for your Product Hunt post
- Use `/pitch/pitch_deck.md` for investor pitch
- Include `README.md`, SEO tags, and CI files

---

## 💡 License
MIT © 2025 Sankalpa Team
"""
        for feat in features:
            content += f"- {feat}\n"
        content += """\n## Getting Started\n\nRun the following commands:\n```bash\nnpm install\nnpm run dev\n```\n\n## Deployment\nSee `/scripts/deploy.sh` or use Vercel CLI.\n"""
        return {
            "message": "README.md content generated.",
            "files": {
                "README.md": content
            }
        }